import {Component} from "react";
import React from "react";
import {TableHead} from "./elements/TableHead";
import {TableRow} from "./elements/TableRow";
import {ColumnHeader} from "./elements/ColumnHeader";
import {TableBody} from "./elements/TableBody";
import {TableData} from "./elements/TableData";
import {Table} from "./elements/Table";
import './FancyTable.css';

class FancyTable extends Component {

  render() {
    return (
      <div className={'table-wrapper'}>
        <Table>
          <TableHead>
            <TableRow>
              <ColumnHeader/>
              <ColumnHeader>A</ColumnHeader>
              <ColumnHeader>B</ColumnHeader>
              <ColumnHeader>C</ColumnHeader>
              <ColumnHeader>D</ColumnHeader>
              <ColumnHeader>E</ColumnHeader>
              <ColumnHeader>F</ColumnHeader>
              <ColumnHeader>G</ColumnHeader>
              <ColumnHeader>H</ColumnHeader>
              <ColumnHeader>I</ColumnHeader>
              <ColumnHeader>J</ColumnHeader>
              <ColumnHeader>K</ColumnHeader>
              <ColumnHeader>L</ColumnHeader>
              <ColumnHeader>M</ColumnHeader>
              <ColumnHeader>N</ColumnHeader>
              <ColumnHeader>O</ColumnHeader>
              <ColumnHeader>P</ColumnHeader>
              <ColumnHeader>Q</ColumnHeader>
              <ColumnHeader>R</ColumnHeader>
              <ColumnHeader>S</ColumnHeader>
              <ColumnHeader>T</ColumnHeader>
              <ColumnHeader>U</ColumnHeader>
              <ColumnHeader>V</ColumnHeader>
              <ColumnHeader>W</ColumnHeader>
              <ColumnHeader>X</ColumnHeader>
              <ColumnHeader>Y</ColumnHeader>
              <ColumnHeader>Z</ColumnHeader>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              <TableData>Anna</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
              <TableData>1</TableData>
            </TableRow>
            <TableRow>
              <TableData>James</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
              <TableData>2</TableData>
            </TableRow>
            <TableRow>
              <TableData>Jennifer</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
              <TableData>3</TableData>
            </TableRow>
            <TableRow>
              <TableData>Jeremiah</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
              <TableData>4</TableData>
            </TableRow>
            <TableRow>
              <TableData>Jocelyn</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
              <TableData>5</TableData>
            </TableRow>
            <TableRow>
              <TableData>Benjamin</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
              <TableData>6</TableData>
            </TableRow>
            <TableRow>
              <TableData>Zed</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
              <TableData>7</TableData>
            </TableRow>
            <TableRow>
              <TableData>Frank</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
              <TableData>8</TableData>
            </TableRow>
            <TableRow>
              <TableData>Chris</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
              <TableData>9</TableData>
            </TableRow>
            <TableRow>
              <TableData>Sarah</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
              <TableData>10</TableData>
            </TableRow>
            <TableRow>
              <TableData>Rob</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
              <TableData>11</TableData>
            </TableRow>
            <TableRow>
              <TableData>Danielle</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
              <TableData>12</TableData>
            </TableRow>
            <TableRow>
              <TableData>Jessica</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
              <TableData>13</TableData>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    )
  }
}

export default FancyTable;